apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
    env: test
  type: NodePort
  ports:
  - name: nginx
    port: 80
    nodePort: 30001
    protocol: TCP
    
