apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3 
  selector:
    app: nginx
    env: test
    
  template:
    metadata:
      labels:
        app: nginx
        env: test
        
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

