apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jenkins
        ver: 2.164.2
    spec:
      containers:
      - name: jenkins
        image: vsuryateja/jenkins:2.164.2
        ports:
        - containerPort: 8080

