apiVersion: v1
kind: Service
metadata:
  name:  jenkins-service
spec:
  selector:
    app: jenkins
    ver: 2.164.2
  type: NodePort
  ports:
  - name: jenkins
    port: 8080
    nodePort: 30003
    protocol: TCP
