FROM tomcat:8.0
LABEL author="surya"
ADD https://downloads.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_2.1.3/openmrs.war /usr/local/tomcat/webapps/openmrs.war
EXPOSE 8080
CMD [ "catalina.sh", "run" ]
