apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    app: hello-world
    ver: v1 
  type: NodePort
  ports:
  - name: hello-world-ports
    port: 8080
    nodePort: 30002
    protocol: TCP

