apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello_world
spec:
  containers:
  - name: hello-world
    image: vsuryateja/hello-world:1-0-0-SNAPSHOT
    ports:
    - containerPort: 8080
   
  
