apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  repicas: 2
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
        ver: 1.0
    spec:
      containers:
      - name: simple-pod
        image:  image
        ports:
        - containerPort: 80